cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

coupons/urls.py
from django.conf.urls import url
from . import views

app_name="coupons"
urlpatterns = [
    url(r'^apply/$', views.coupon_apply, name='apply'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name="orders"
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.admin_order_detail, name='admin_order_detail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.admin_order_pdf, name='admin_order_pdf'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name="producthunt"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include(('cart.urls'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

app_name="shop"
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES,
                                      coerce=int, label='',)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')




def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    coupon_apply_form = CouponApplyForm()

    return render(request, 'cart/detail.html', {'cart': cart,
                                                'coupon_apply_form': coupon_apply_form})

cart/templates/cart/detail.html
{% extends "shop/base_2.html" %}
{% load static %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block content %}
<style>
.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
}
.form-signin .form-control:focus {
  z-index: 2;
}

</style>


<!--Main layout-->
<main class="mt-5 pt-4">
  <div class="container wow fadeIn">

    <!--Grid row-->
    <div class="row">

      <!--Grid column-->
      <div class="col-md-8 mb-4">

        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Your cart</span>
          {% with total_items=cart|length %}
          <span class="badge pink lighten-3 badge-pill">{{ total_items }}</span>
          {% endwith %}
        </h4>

        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
          {% for item in cart %}
              {% with product=item.product %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{ product.name }}x{{ item.quantity}}</h6>
                  <small class="text-muted"><a href="{% url "cart:cart_remove" product.id %}">删除</a></small>
                </div>

                <span class="text-muted"> ${{ item.total_price }}</span>
              </li>
<!--
          <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
              <h6 class="my-0">${{ item.price }}/each x {{ item.quantity}}</h6>
              <small class="text-muted">{{ product.name }}</small>
            </div>
            <span class="text-muted"><a href="{% url "cart:cart_remove" product.id %}"><i class="fa fa-times" aria-hidden="true"></i></a></span>
            <span class="text-muted">&nbsp;&nbsp;</span>
            <span class="text-muted"> ${{ item.total_price }}</span>
          </li>
        -->
          {% endwith %}
      {% endfor %}
      <li class="list-group-item d-flex justify-content-between">
        <span></span>
        <strong><a href="{% url "shop:product_list" %}" >继续购物 </a></strong>
      </li>
      {% if user.is_authenticated %}
      <li class="list-group-item d-flex justify-content-between">
        <span></span>
        <a href="{% url "orders:order_create" %}"> 去结算</a>
      </li>
      {% else %}
      <li class="list-group-item d-flex justify-content-between">
        <span></span>
        <a href="{% url 'login' %}"> 去结算</a>
      </li>
      {% endif %}

        </ul>
        <!-- Cart -->



      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-4 mb-4">

        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">商品金额</span>
          <span class="text-success"><h6>购物满$100免运费</h6></span>
        </h4>

        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
          {% if cart.coupon %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">折扣码</h6>
              <small>{{ cart.coupon.code }}({{ cart.coupon.discount }}% off)</small>
            </div>
            <span class="text-success">- ${{ cart.get_discount|floatformat:"2" }}</span>
          </li>
          {% endif %}

          {% if cart.get_total_price_after_discount < 100 %}
          <li class="list-group-item d-flex justify-content-between bg-light">
            <div class="text-success">
              <h6 class="my-0">运费</h6>
            </div>
            <span class="text-success">+$7.00</span>
          </li>


          <li class="list-group-item d-flex justify-content-between">
            <span>合计总额 (USD)</span>
            <strong>${{ cart.get_total_price_with_shippingfee|floatformat:"2" }}</strong>
          </li>
          {% else %}

          <li class="list-group-item d-flex justify-content-between">
            <span>合计总额 (USD)</span>
            <strong>${{ cart.get_total_price_after_discount|floatformat:"2" }}</strong>
          </li>
          {% endif %}
        </ul>
        <!-- Cart -->

        <!-- Promo code -->
        <form class="card p-2" action="{% url "coupons:apply" %}" method="post">
          <div class="md-form">
            <h6>折扣码：</h6>
            {{ coupon_apply_form }}
            {% csrf_token %}
          </div>
          <div class="input-group-append">
            <button type="submit" class="btn pink lighten-3">使用</button>
          </div>
        </form>
        <!-- Promo code -->

      </div>
      <!--Grid column-->

    </div>
    <!--Grid row-->

  </div>

</main>
<!--Main layout-->
<br>

<div class="container">

<!--Section: Features v.1-->
<section class="text-center">


    <!--Grid row-->
    <div class="row">

    <!--Grid column-->
    <div class="col-md-4">
        <i class="fa fa-truck fa-3x grey-text"></i>
        <h5 class="font-weight-bold mt-3">Free Shipping</h5>
        <p class="grey-text">Free shipping for all orders over $100</p>
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-4">
        <i class="fa fa-refresh fa-3x grey-text"></i>
        <h5 class="font-weight-bold mt-3">Money Back Guarantee</h5>
        <p class="grey-text">We return money within 30 days</p>
    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-4">
        <i class="fa fa-comments-o fa-3x grey-text"></i>
        <h5 class="font-weight-bold mt-3">24/7 Customer Support</h5>
        <p class="grey-text">Friendly 24/7 customer support</p>
    </div>
    <!--Grid column-->

    </div>
    <!--Grid row-->

</section>
<!--Section: Features v.1-->


</div>

{% endblock %}