cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name="producthunt"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include(('cart.urls'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

app_name="shop"
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def shorttitle(self):
        return self.name[:10]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


def product_list(request, category_slug=None):
    limit = 8  # 每页显示的记录数
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, limit)  # 实例化一个分页对象
    page = request.GET.get('page')  # 获取页码
    try:
        products = paginator.page(page)  # 获取某页对应的记录
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if category_slug:
        limit = 8
        products = Product.objects.filter(available=True)
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        paginator = Paginator(products, limit)  # 实例化一个分页对象
        page = request.GET.get('page')  # 获取页码
        try:
            products = paginator.page(page)  # 获取某页对应的记录
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/product/detail.html
{% extends "shop/base_2.html" %}
{% load static %}

{% block content %}

    <!--Main layout-->
    <main class="mt-5 pt-4">
      <div class="container dark-grey-text mt-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 mb-4">

            <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid" alt="">

          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-md-6 mb-4">

            <!--Content-->
            <div class="p-4">

              <div class="mb-3">
                <a href="">
                  <span class="badge blue mr-1">{{ product.category }}</span>
                </a>
                <a href="">
                  <span class="badge pink lighten-3 mr-1">Bestseller</span>
                </a>
              </div>

              <p class="lead">
                <span>${{ product.price }}</span>
              </p>

              <p class="lead font-weight-bold">{{ product.name }}</p>

              <p align="justify">{{ product.description }}</p>

              <form action="{% url "cart:cart_add" product.id %}" class="d-flex justify-content-left" method="post">
                <!-- Default input -->

                {{ cart_product_form }}

                {% csrf_token %}

                <button class="btn pink lighten-3 btn-md my-0 p" type="submit">加入购物车
                  <i class="fa fa-shopping-cart ml-1"></i>
                </button>

              </form>

            </div>
            <!--Content-->

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <hr>

        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">

          <!--Grid column-->
          <div class="col-md-6 text-center">

            <h4 class="my-4 h4">Additional Information</h4>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit voluptates,
              quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
              <a class="nav-link" href="{{ product.category.get_absolute_url }}">相似商品</a>

          </div>
          <!--Grid column-->

        </div>
        <!--Grid row-->

        <!--Grid row
        <div class="row wow fadeIn">


          <div class="col-lg-3 col-md-3 mb-3">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

          </div>

          <div class="col-lg-3 col-md-3 mb-3">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

          </div>

          <div class="col-lg-3 col-md-3 mb-3">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

          </div>

          <div class="col-lg-3 col-md-3 mb-3">

            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

          </div>


        </div>
        Grid row-->

      </div>
    </main>
    <!--Main layout-->

{% endblock %}


<div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p class="price">${{ product.price }}</p>
    <form action="{% url "cart:cart_add" product.id %}" method="post">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="Add to cart">
    </form>
    {{ product.description|linebreaks }}
</div>

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}

{% block content %}



    <main>
      <div class="container" >

        <!--Navbar-->
        <nav  class="navbar navbar-expand-lg navbar-dark pink lighten-3 mt-3 mb-5" >

          <!-- Navbar brand -->
          <span class="navbar-brand" >商品分类:</span>

          <!-- Collapse button -->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
          aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav" >

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            <li  {% if not category %} class="nav-item active" {% endif %}>
              <a class="nav-link" href="{% url "shop:product_list" %}">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            {% for c in categories %}
            <li  {% if category.slug == c.slug %} class="nav-item active" {% endif %}>
              <a class="nav-link" href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
            {% endfor %}
          </ul>
          <!-- Links -->

          <form class="form-inline">
            <div class="md-form mt-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">
        <!--Grid row-->
        <div class="row wow fadeIn">
          {% for product in products %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->

                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}" class="img-fluid" alt="">

              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ product.category }}</h5>
                </a>
                <h6>
                  <strong>
                    <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.name }}</a>
                  </strong>
                </h6>

                <h4 class="font-weight-bold blue-text">
                  <strong>${{ product.price }}</strong>
                </h4>

              </div>
              <!--Card content-->
            </div>
            <!--Card-->
          </div>
          {% if forloop.counter|divisibleby:4 %}
          </div>
          <!--Grid column-->
          <div class="row wow fadeIn">
          {% endif %}
          {% endfor %}

        </div>
        <!--Grid row-->
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          <!--Arrow left-->
          {% if products.has_previous %}

          <li class="page-item">
            <a class="page-link" href="?page={{ products.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          {% for page_number in products.paginator.page_range %}
          {% ifequal page_number  products.number %}
          <li class="page-item active">
            <a class="page-link" href="#">{{ page_number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>

          </li>

          {% endifequal %}
          {% endfor %}

          {% if products.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ products.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
    </div>
  </main>
  <!--Main layout-->

{% endblock %}