cart/urls.py
from django.conf.urls import url
from . import views

app_name="cart"
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

producthunt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

app_name="producthunt"
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include(('cart.urls'), namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^coupons/', include('coupons.urls', namespace='coupons')),
    url(r'^', include('shop.urls', namespace='shop')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views

app_name="shop"
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def shorttitle(self):
        return self.name[:10]

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger


def product_list(request, category_slug=None):
    limit = 8  # 每页显示的记录数
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    paginator = Paginator(products, limit)  # 实例化一个分页对象
    page = request.GET.get('page')  # 获取页码
    try:
        products = paginator.page(page)  # 获取某页对应的记录
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    if category_slug:
        limit = 8
        products = Product.objects.filter(available=True)
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
        paginator = Paginator(products, limit)  # 实例化一个分页对象
        page = request.GET.get('page')  # 获取页码
        try:
            products = paginator.page(page)  # 获取某页对应的记录
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {'category': category,
                                                      'categories': categories,
                                                      'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/base_2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>网站名字</title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Bootstrap core CSS -->
  <link href="/static/css/bootstrap.min.css" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="/static/css/mdb.min.css" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="/static/css/style.min.css" rel="stylesheet">

  <style>
  #myBtn {
display: none;
position: fixed;
bottom: 20px;
right: 30px;
z-index: 99;
font-size: 18px;
border: none;
outline: none;
background-color: rgba(0, 0, 0, 0.7);
color: white;
cursor: pointer;
padding: 15px;
border-radius: 4px;
}

#myBtn:hover {
background-color:rgba(0, 0, 0, 0.9);
}
  </style>
</head>

<body>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand font-weight-bold font-italic" href="{% url "shop:product_list" %}"><img src="{% static 'shopping-bag.png' %}" height=35 width=35 class="d-inllie-block alighn-top">
        <strong>网站名字</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="#">首页
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#">专区一</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#" >专区二</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#" >专区三</a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="#">专区四</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                <a href="{% url "cart:cart_detail" %}" class="nav-link waves-effect">
                  <i class="fa fa-shopping-cart"></i>
                  <span class="badge pink lighten-3 z-depth-1 mr-1"> {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }} </span>
                </a>
                {% else %}
                <a class="nav-link waves-effect">
                  <i class="fa fa-shopping-cart"></i>
                  <span class="badge red z-depth-1 mr-1"> 0 </span>
                </a>
                {% endif %}
            {% endwith %}
          </li>
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'myorders' %}" onclick=""><i class="fa fa-shopping-bag"></i> &nbsp;我的订单 </a> &nbsp;&nbsp;
            <a class="nav-link" href="javascript:{document.getElementById('logout').submit()}" onclick=""><i class="fa fa-sign-out"></i>&nbsp;注销</a>
            <form id="logout" method="POST" action="{% url 'logout' %}">
              {% csrf_token %}
              <input type="hidden">
            </form>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link waves-effect">
              <i class="fa fa-sign-in" aria-hidden="true"></i> 登陆
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'signup' %}" class="nav-link waves-effect"
              >
              <i class="fa fa-user-plus" aria-hidden="true"></i> 注册
            </a>
          </li>
          {% endif %}
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->
<br>
<br>
  <!--Main layout-->
  <main>
      {% block content %}
      {% endblock %}
      <button onclick="topFunction()" id="myBtn" title="Go to top"<i class='fa fa-chevron-up'></i></button>
        <script>
    // When the user scrolls down 20px from the top of the document, show the button
    window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("myBtn").style.display = "block";
        } else {
            document.getElementById("myBtn").style.display = "none";
        }
    }

    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
    </script>
  </main>
  <!--Main layout-->



    <!--Footer-->
    <footer class="page-footer font-small blue-grey lighten-5 pt-0 ">

        <div style="background-color:#f48fb1;">
            <div class="container">
                <!--Grid row-->
                <div class="row py-4 d-flex align-items-center">

                    <!--Grid column-->
                    <div class="col-12 col-md-5 text-left mb-4 mb-md-0">
                        <h6 class="mb-0 white-text text-center text-md-left">
                            <strong>Get connected with us on social networks!</strong>
                        </h6>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-12 col-md-7 text-center text-md-right">
                        <!--Facebook-->
                        <a class="fb-ic ml-0">
                            <i class="fa fa-facebook white-text mr-lg-4"> </i>
                        </a>
                        <!--Twitter-->
                        <a class="tw-ic">
                            <i class="fa fa-twitter white-text mr-lg-4"> </i>
                        </a>
                        <!--Google +-->
                        <a class="gplus-ic">
                            <i class="fa fa-google-plus white-text mr-lg-4"> </i>
                        </a>
                        <!--Linkedin-->
                        <a class="li-ic">
                            <i class="fa fa-linkedin white-text mr-lg-4"> </i>
                        </a>
                        <!--Instagram-->
                        <a class="ins-ic">
                            <i class="fa fa-instagram white-text mr-lg-4"> </i>
                        </a>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->
            </div>
        </div>

        <!--Footer Links-->
        <div class="container mt-5 mb-4 text-center text-md-left ">
            <div class="row mt-3">

                <!--First column-->
                <div class="col-md-3 col-lg-4 col-xl-3 mb-4 dark-grey-text">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>网站名字</strong>
                    </h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>这里是网站的简介。</p>
                </div>
                <!--/.First column-->

                <!--Second column-->
                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 dark-grey-text">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>网站地图</strong>
                    </h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <a href="#!" class="dark-grey-text">首页</a>
                    </p>
                    <p>
                        <a href="#!" class="dark-grey-text">最热折扣</a>
                    </p>
                    <p>
                        <a href="#!" class="dark-grey-text">折扣码</a>
                    </p>
                </div>
                <!--/.Second column-->

                <!--Third column-->
                <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4 dark-grey-text">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>帮助</strong>
                    </h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <a href="#!" class="dark-grey-text">问题反馈</a>
                    </p>
                    <p>
                        <a href="#!" class="dark-grey-text">加入我们</a>
                    </p>
                    <p>
                        <a href="#!" class="dark-grey-text">广告合作</a>
                    </p>

                </div>
                <!--/.Third column-->

                <!--Fourth column-->
                <div class="col-md-4 col-lg-3 col-xl-3 dark-grey-text">
                    <h6 class="text-uppercase font-weight-bold">
                        <strong>联系我们</strong>
                    </h6>
                    <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
                    <p>
                        <i class="fa fa-envelope mr-3"></i> info@example.com</p>
                    <p>
                        <i class="fa fa-phone mr-3"></i>(123)456-7899</p>
                </div>
                <!--/.Fourth column-->

            </div>
        </div>
        <!--/.Footer Links-->

        <!-- Copyright-->
        <div class="footer-copyright py-3 text-center pink lighten-3">
            © 2018 Copyright:
            <a href="#">
                <strong>网站名字</strong>
            </a>
        </div>
        <!--/.Copyright -->

    </footer>
    <!--/.Footer-->



  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="/static/js/jquery-3.2.1.min.js"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="/static/js/popper.min.js"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="/static/js/mdb.min.js"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

shop/templates/shop/base_3.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
    <div id="header">
        <a href="/" class="logo">My shop</a>
    </div>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>